dvpOAuth/__init__.py,sha256=5sqDq88TzdVr96Yb3ZC3dAAABf-0ALh--SRxNdrQtMc,163
dvpOAuth/class_OAuth.py,sha256=pLfXdKh4FtdzUxRmNt7UI1ievvBvEt9BvVjCbAc-pto,16804
dvpOAuth/error.py,sha256=Y3BjsevsSGMDVVdn6ztiQMcGNtB6lySkNPoL7y4BT-Q,131
dvpOAuth/util.py,sha256=StyBKMaC0y7HgElnOvIuG8qtledp3Of6OadfERm4yCg,591
dvpOAuth-0.0.20.dist-info/LICENSE,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
dvpOAuth-0.0.20.dist-info/METADATA,sha256=_7-E5QDPIW8w3Jby5wjSmP5mfXvTT8SzlNjSr3toYPo,992
dvpOAuth-0.0.20.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
dvpOAuth-0.0.20.dist-info/top_level.txt,sha256=14UgmlstFHh0UvlWIljRlFO26u2OesXzFC8SsWFZRmw,9
dvpOAuth-0.0.20.dist-info/RECORD,,
