pyodbc.cpython-36m-aarch64-linux-gnu.so,sha256=wpZ6f8Cruhnv8CPptDIf5fcJvEcV52SKLSIhGs03-i0,989480
pyodbc.pyi,sha256=JWNpdgmrxhNioTjW6OoAEcXELcGZobcMYzKtYlcJRuY,32320
pyodbc-4.0.38.dist-info/WHEEL,sha256=ZPo-cudG-FPYxyq1LXmKAMnRyaidvTmBVvSIj1CJfHY,152
pyodbc-4.0.38.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.38.dist-info/RECORD,,
pyodbc-4.0.38.dist-info/METADATA,sha256=uQiX0gZrhbZAadzgdRRPh43nQLecgG0BXB_DuOHqiiY,3180
pyodbc-4.0.38.dist-info/top_level.txt,sha256=Rb69vS-SNN_Bfh99vX7eCcvEAJoyzowG3u4R7W36Flw,8
